const db = require('./db');

const TIPIFICACION_A_AREA_MAP = {
  // 1. NORMALIZACIÓN
  'NORMALIZACIÓN': 'NORMALIZACIÓN',
  'NORMALIZACION': 'NORMALIZACIÓN',
  'NORMALIZACION FINALIZADA': 'NORMALIZACIÓN',
  'NORMALIZACION FINALIZADA BRAZO EXTENSOR': 'NORMALIZACIÓN',
  'REMATRICULACION ONT': 'NORMALIZACIÓN',
  'MIGRA GAMER REALIZADO - POSTVENTA': 'NORMALIZACIÓN',
  'MIGRA GAMER SOLO ENTREGA': 'NORMALIZACIÓN',
  'MIGRA GAMER': 'NORMALIZACIÓN',
  'MIGRA XGSPON': 'NORMALIZACIÓN',
  'CAMBIO DE ONT - MEJORA TECNOLOGICA': 'NORMALIZACIÓN',
  'MEJORA TECNOLOGICA MESH': 'NORMALIZACIÓN',
  'MEJORA TECNOLOGICA ONT': 'NORMALIZACIÓN',

  // 2. GARANTIA Y GARANTIA NO REALIZADA
  'GARANTIA': 'GARANTIA',
  'GARANTIA REALIZADA': 'GARANTIA',
  'POST VENTA GARANTIA': 'GARANTIA',
  'GARANTIA NO REALIZADA': 'GARANTIA NO REALIZADA',
  'GARANTIA CANCELADA': 'GARANTIA NO REALIZADA',
  'GARANTIA REPROGRAMADA': 'GARANTIA NO REALIZADA',
  'GARANTIA OBSERVADA': 'GARANTIA NO REALIZADA',

  // 3. RECABLEADO EN CONDOMINIO
  'SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO - VISITA TECNICA': 'RECABLEADO EN CONDOMINIO',
  'RECABLEADO EN CONDOMINIO': 'RECABLEADO EN CONDOMINIO',
  'RECABLEADO CONDOMINIO': 'RECABLEADO EN CONDOMINIO',

  // 4. RECABLEADO
  'SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL - VISITA TECNICA': 'RECABLEADO',
  'SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL - POST VENTA': 'RECABLEADO',
  'SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO - POST VENTA': 'RECABLEADO',
  'RECABLEADO - AVERIADO POR TERCEROS': 'RECABLEADO',
  'RECABLEADO - CLIENTE MIGRA A OTRA CTO': 'RECABLEADO',
  'RECABLEADO - POST VENTA': 'RECABLEADO',
  'RECABLEADO - AVERIADO POR CLIENTE': 'RECABLEADO',
  'RECABLEADO - CAMBIO DE POSTE': 'RECABLEADO',
  'RECABLEADO - NO CUMPLE POLITICAS DE INSTALACION': 'RECABLEADO',
  'RECABLEADO + CAMBIO DE ONT POST VENTA': 'RECABLEADO',
  'RECABLEADO CORTE MUNICIPAL': 'RECABLEADO',
  'RECABLEADO - DESCONEXION DEL CLIENTE': 'RECABLEADO',
  'RECABLEADO + WIN BOX': 'RECABLEADO',
  'RECABLEADO + CABLEADO MESH + 1 MESH': 'RECABLEADO',
  'RECABLEADO + 1 MESH': 'RECABLEADO',
  'RECABLEADO + CAMBIO DE ONT + CABLEADO MESH + 1 MESH': 'RECABLEADO',
  'RECABLEADO + CABLEADO MESH - POSTVENTA': 'RECABLEADO',
  'RECABLEADO POR CORTE CONCESIONARIA': 'RECABLEADO',
  'RECABLEADO POR MANTENIMIENTO': 'RECABLEADO',
  'RECABLEADO + 2 WIN BOX': 'RECABLEADO',
  'RECABLEADO + 2 MESH': 'RECABLEADO',
  'RECABLEADO': 'RECABLEADO',

  // 5. REUBICACIÓN CON RESERVA
  'REUBICACION DE ROUTER CON RESERVA - POST VENTA': 'REUBICACIÓN CON RESERVA',
  'REUBICACION CON RESERVA': 'REUBICACIÓN CON RESERVA',
  'REUBICACIÓN CON RESERVA': 'REUBICACIÓN CON RESERVA',

  // 6. REUBICACIÓN SIN RESERVA
  'REUBICACION DE ROUTER SIN RESERVA - POST VENTA': 'REUBICACIÓN SIN RESERVA',
  'REUBICACION SIN RESERVA': 'REUBICACIÓN SIN RESERVA',
  'REUBICACIÓN SIN RESERVA': 'REUBICACIÓN SIN RESERVA',
  'REUBICACION SIN RESERVA / CON RESERVA + CABLEADO MESH - POSTVENTA': 'REUBICACIÓN SIN RESERVA',

  // 7. TRASALDO EN CONDOMINIO
  'TRASLADO DE SERVICIOS POR MUDANZA EN CONDOMINIO - POST VENTA': 'TRASALDO EN CONDOMINIO',
  'TRASALDO EN CONDOMINIO': 'TRASALDO EN CONDOMINIO',
  'TRASLADO EN CONDOMINIO': 'TRASALDO EN CONDOMINIO',

  // 8. TRASLADO
  'TRASLADO DE SERVICIOS POR MUDANZA EN RESIDENCIALES - POST VENTA': 'TRASLADO',
  'TRASLADO': 'TRASLADO',
  'TRASLADO + CAMBIO ONT': 'TRASLADO',
  'TRASLADO + 1 MESH': 'TRASLADO',
  'TRASLADO + CABLEADO MESH - POSTVENTA': 'TRASLADO',
  'TRASLADO + 1 WIN BOX': 'TRASLADO',
  'TRASLADO + CAMBIO DE ONT + 1 MESH': 'TRASLADO',
  'TRASLADO + CABLEADO MESH + 1 MESH': 'TRASLADO',
  'TRASLADO + 1 APARATO TELEFONICO': 'TRASLADO',

  // 9. PEX
  'PRUEBA DE SERVICIO - CTO CON POTENCIA DEGRADADA': 'PEX',
  'PRUEBA DE SERVICIO - CTO CON PUERTOS DEGRADADOS': 'PEX',
  'PRUEBA DE SERVICIO': 'PEX',
  'PRUEBAS DE SERVICIO': 'PEX',
  'PRUEBA DE SERVICIO - CTO O NAP CON PROBLEMAS DE POTENCIA EN PUERTOS': 'PEX',
  'PRUEBA DE SERVICIO - CTO SIN POTENCIA': 'PEX',
  'CONJUNTA FINALIZADA': 'PEX',
  'CONJUNTA PEXT AVERIA': 'PEX',
  'CONJUNTA PEXT': 'PEX',
  'PRUEBA DE SERVICIO - CTO CON INTERMITENCIA': 'PEX',
  'PRUEBA DE SERVICIO - NAP SIN POTENCIA': 'PEX',
  'PRUEBA DE SERVICIO - NAP CON PUERTOS DEGRADADOS': 'PEX',
  'PRUEBA DE SERVICIO - NAP CON POTENCIA DEGRADADA': 'PEX',
  'TRABAJOS PLANTA EXTERNA': 'PEX',
  'PEX': 'PEX',

  // 10. ADICIONAL
  'INSTALACION DE SPLITERS 1X2': 'ADICIONAL',
  'INSTALACION DE SPLITTERS 1X2': 'ADICIONAL',
  'SPLITTER': 'ADICIONAL',
  'SPLITER': 'ADICIONAL',
  'CAMBIO DE MESH ADICIONAL': 'ADICIONAL',
  'CAMBIO DE TV BOX ADICIONAL': 'ADICIONAL',
  'CAMBIO DE ONT POR REPOSICION ADICIONAL': 'ADICIONAL',
  'CABLEADO UTP CAT 6 ADICIONAL - POST VENTA': 'ADICIONAL',
  'SERVICIO DE ENTREGA Y CONFIGURACION DE FONO WIN - ADICIONAL': 'ADICIONAL',
  'SERVICIO DE ENTREGA Y CONFIGURACION DE TV BOX - ADICIONAL': 'ADICIONAL',
  'SERVICIOS DE ENTREGA Y CONFIGURACION MESH - ADICIONAL': 'ADICIONAL',
  'KIT WIFI PRO (AL CONTADO)': 'ADICIONAL',
  'CABLEADO UTP AL CONTADO': 'ADICIONAL',
  '1 APARATO TELEFONICO': 'ADICIONAL',
  '1 MESH': 'ADICIONAL',
  '2 MESH': 'ADICIONAL',
  '1 WIN BOX': 'ADICIONAL',
  '2 WIN BOX': 'ADICIONAL',
  'ADICIONAL': 'ADICIONAL',

  // 11. VISITA EXTERNA
  'CAMBIO DE EQUIPO ONT': 'VISITA EXTERNA',
  'CAMBIO DE ONT ADICIONAL': 'ADICIONAL',
  'CAMBIO FONOWIN': 'VISITA EXTERNA',
  'CAMBIO DE FONO WIN': 'VISITA EXTERNA',
  'CAMBIO DE CONECTOR EN CTO/NAP': 'VISITA EXTERNA',
  'CAMBIO DE CONECTOR CTO/NAP': 'VISITA EXTERNA',
  'CAMBIO DE CONECTOR EN ROSETA': 'VISITA EXTERNA',
  'ADAPTADOR ROSETA': 'VISITA EXTERNA',
  'CAMBIO DE CABLE PATCH CORD': 'VISITA EXTERNA',
  'CAMBIO DE CABLE PATCHCORD': 'VISITA EXTERNA',
  'CAMBIO DE PATCH CORD': 'VISITA EXTERNA',
  'PATCH CORD': 'VISITA EXTERNA',
  'PATCH CORD - POST VENTA': 'VISITA EXTERNA',
  'CAMBIO DE ACOPLADOR': 'VISITA EXTERNA',
  'ACOMODO DE FIBRA': 'VISITA EXTERNA',
  'ACONDICIONAMIENTO DE DROP': 'VISITA EXTERNA',
  'ATENCION DE AVERIAS ULTIMA MILLA': 'VISITA EXTERNA',
  'ATENCION DE AVERIA ULTIMA MILLA': 'VISITA EXTERNA',
  'CAMBIO DE TV BOX': 'VISITA EXTERNA',
  'CAMBIO DE WINBOX': 'VISITA EXTERNA',
  'CONFIGURACION WINBOX': 'VISITA EXTERNA',
  'CONFIGURACION MESH': 'VISITA EXTERNA',
  'CONFIGURACION ONT': 'VISITA EXTERNA',
  'CONFIGURACION PHONOWIN': 'VISITA EXTERNA',
  'CAMBIO DE EQUIPO MESH': 'VISITA EXTERNA',
  'CAMBIO MESH - NO SINCRONIZA / NO EMITE SEÑAL': 'VISITA EXTERNA',
  'CAMBIO MESH - MESH INOPERATIVO': 'VISITA EXTERNA',
  'CAMBIO MESH - PUERTOS AVERIADOS': 'VISITA EXTERNA',
  'CAMBIO DE ONT - ONT INOPERATIVA': 'VISITA EXTERNA',
  'CAMBIO DE ONT - NO SINCRONIZA / NO EMITE SEÑAL': 'VISITA EXTERNA',
  'CAMBIO DE ONT - CARGADOR MALOGRADO': 'VISITA EXTERNA',
  'CAMBIO DE ONT - ONT ROBADA': 'VISITA EXTERNA',
  'CAMBIO DE ONT - PUERTOS AVERIADOS': 'VISITA EXTERNA',
  'CAMBIO ONT - POST VENTA': 'VISITA EXTERNA',
  'CAMBIO DE ONT + 1 WIN BOX': 'VISITA EXTERNA',
  'CABLEADO MESH - POSTVENTA': 'VISITA EXTERNA',
  'CABLEADO MESH + 1 WIN BOX': 'VISITA EXTERNA',
  'CABLEADO MESH + 1 MESH + CAMBIO DE ONT': 'VISITA EXTERNA',
  'CABLEADO 02 MESH - POSTVENTA': 'VISITA EXTERNA',
  'CABLEADO 03 MESH - POSTVENTA': 'VISITA EXTERNA',
  'CABLEADO MESH + 2 MESH + CAMBIO DE ONT': 'VISITA EXTERNA',
  'CABLEADO MESH + 2 WIN BOX': 'VISITA EXTERNA',
  'ENTREGA + CONFIG 1 WIN BOX': 'VISITA EXTERNA',
  'ENTREGA + CONFIG 2 WIN BOX': 'VISITA EXTERNA',
  'ENTREGA + CONFIG 1 MESH': 'VISITA EXTERNA',
  'ENTREGA + CONFIG 2 MESH': 'VISITA EXTERNA',
  'ENTREGA + CONFIG 1 MESH + 1 WIN BOX': 'VISITA EXTERNA',
  'ENTREGA + CONFIG 1 MESH + APARATO TEL': 'VISITA EXTERNA',
  'ENTREGA + CONFIG 1 APARATO TELEFONICO': 'VISITA EXTERNA',
  'ASISTENCIA WIN TV': 'VISITA EXTERNA',
  'ASISTENCIA DGO': 'VISITA EXTERNA',
  'CONFIG CREDENCIALES DGO': 'VISITA EXTERNA',
  'CONFIG CREDENCIALES APPS': 'VISITA EXTERNA',
  'CONFIG CREDENCIALES WIN TV': 'VISITA EXTERNA',
  'WINBOX - CONTROL DEFECT': 'VISITA EXTERNA',
  'CLIENTE CON SERVICIO - POTENCIA OPTIMA': 'VISITA EXTERNA',
  'VISITA EXTERNA': 'VISITA EXTERNA'
};

async function run() {
  console.log('Iniciando sincronizacion de motivos...');
  const [existing] = await db.query('SELECT id_motivo, nombre, tipo_trabajo, limites_materiales FROM motivos');
  const existingMap = new Map();
  for (const row of existing) {
    existingMap.set(row.nombre.toUpperCase().trim(), row);
  }

  let insertCount = 0;
  let updateCount = 0;

  for (const [nombre, tipo_trabajo] of Object.entries(TIPIFICACION_A_AREA_MAP)) {
    const cleanNombre = nombre.trim();
    const key = cleanNombre.toUpperCase();

    if (existingMap.has(key)) {
      const row = existingMap.get(key);
      if (row.tipo_trabajo !== tipo_trabajo) {
        await db.query('UPDATE motivos SET tipo_trabajo = ? WHERE id_motivo = ?', [tipo_trabajo, row.id_motivo]);
        updateCount++;
      }
    } else {
      await db.query(
        'INSERT INTO motivos (nombre, tipo_trabajo, precio_compra, precio_venta, limites_materiales, estado, fecha_creacion) VALUES (?, ?, ?, ?, ?, ?, NOW())',
        [cleanNombre, tipo_trabajo, '90.00', '40.00', null, 'Activo']
      );
      insertCount++;
    }
  }

  console.log('Insertados: ' + insertCount + ', Actualizados: ' + updateCount);
  const [total] = await db.query('SELECT COUNT(*) AS c FROM motivos');
  console.log('Total registros en tabla motivos: ' + total[0].c);
  process.exit();
}

run();
