/**
 * Mapeo oficial entre Tipo de Liquidación (Tipificación WIN / Motivo de Finalización / Avería)
 * y el Tipo de Trabajo (Área) según la tabla MySQL `tipos_trabajo` y la matriz de homologación.
 */

export const TIPOS_TRABAJO_CATALOGO = [
  "NORMALIZACIÓN",
  "RECABLEADO",
  "GARANTIA",
  "REUBICACIÓN CON RESERVA",
  "TRASLADO",
  "VISITA EXTERNA",
  "REUBICACIÓN SIN RESERVA",
  "GARANTIA NO REALIZADA",
  "RECABLEADO EN CONDOMINIO",
  "TRASALDO EN CONDOMINIO",
  "PEX",
  "ADICIONAL",
];

// Tabla de mapeo exacto normalizado
const TIPIFICACION_A_AREA_MAP: Record<string, string> = {
  // 1. NORMALIZACIÓN
  "NORMALIZACION": "NORMALIZACIÓN",
  "NORMALIZACION FINALIZADA": "NORMALIZACIÓN",
  "NORMALIZACION FINALIZADA BRAZO EXTENSOR": "NORMALIZACIÓN",
  "NORMALIZACION CANCELADA": "NORMALIZACIÓN",
  "REMATRICULACION ONT": "NORMALIZACIÓN",
  "MIGRA GAMER REALIZADO - POSTVENTA": "NORMALIZACIÓN",
  "MIGRA GAMER REALIZADO POSTVENTA": "NORMALIZACIÓN",
  "MIGRA GAMER SOLO ENTREGA": "NORMALIZACIÓN",
  "MIGRA GAMER": "NORMALIZACIÓN",
  "MIGRA XGSPON": "NORMALIZACIÓN",
  "CAMBIO DE ONT - MEJORA TECNOLOGICA": "NORMALIZACIÓN",
  "CAMBIO DE ONT MEJORA TECNOLOGICA": "NORMALIZACIÓN",
  "CAMBIO DE ONT - MEJORA TECNOLOGICA - POSTVENTA": "NORMALIZACIÓN",
  "CAMBIO DE ONT MEJORA TECNOLOGICA POSTVENTA": "NORMALIZACIÓN",
  "MEJORA TECNOLOGICA MESH": "NORMALIZACIÓN",
  "MEJORA TECNOLOGICA ONT": "NORMALIZACIÓN",

  // 2. GARANTIA Y GARANTIA NO REALIZADA
  "GARANTIA": "GARANTIA",
  "GARANTIA REALIZADA": "GARANTIA",
  "POST VENTA GARANTIA": "GARANTIA",
  "GARANTIA NO REALIZADA": "GARANTIA NO REALIZADA",
  "GARANTIA CANCELADA": "GARANTIA NO REALIZADA",
  "GARANTIA REPROGRAMADA": "GARANTIA NO REALIZADA",
  "GARANTIA OBSERVADA": "GARANTIA NO REALIZADA",

  // 3. RECABLEADO EN CONDOMINIO
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO - VISITA TECNICA": "RECABLEADO EN CONDOMINIO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO VISITA TECNICA": "RECABLEADO EN CONDOMINIO",
  "RECABLEADO EN CONDOMINIO": "RECABLEADO EN CONDOMINIO",
  "RECABLEADO CONDOMINIO": "RECABLEADO EN CONDOMINIO",

  // 4. RECABLEADO
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL - VISITA TECNICA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL VISITA TECNICA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL - POST VENTA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL POST VENTA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO - POST VENTA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO POST VENTA": "RECABLEADO",
  "RECABLEADO - AVERIADO POR TERCEROS": "RECABLEADO",
  "RECABLEADO AVERIADO POR TERCEROS": "RECABLEADO",
  "RECABLEADO - CLIENTE MIGRA A OTRA CTO": "RECABLEADO",
  "RECABLEADO CLIENTE MIGRA A OTRA CTO": "RECABLEADO",
  "RECABLEADO - POST VENTA": "RECABLEADO",
  "RECABLEADO POST VENTA": "RECABLEADO",
  "RECABLEADO - AVERIADO POR CLIENTE": "RECABLEADO",
  "RECABLEADO AVERIADO POR CLIENTE": "RECABLEADO",
  "RECABLEADO - CAMBIO DE POSTE": "RECABLEADO",
  "RECABLEADO CAMBIO DE POSTE": "RECABLEADO",
  "RECABLEADO - NO CUMPLE POLITICAS DE INSTALACION": "RECABLEADO",
  "RECABLEADO NO CUMPLE POLITICAS DE INSTALACION": "RECABLEADO",
  "RECABLEADO + CAMBIO DE ONT POST VENTA": "RECABLEADO",
  "RECABLEADO CAMBIO DE ONT POST VENTA": "RECABLEADO",
  "RECABLEADO CORTE MUNICIPAL": "RECABLEADO",
  "RECABLEADO - DESCONEXION DEL CLIENTE": "RECABLEADO",
  "RECABLEADO DESCONEXION DEL CLIENTE": "RECABLEADO",
  "RECABLEADO + WIN BOX": "RECABLEADO",
  "RECABLEADO + CABLEADO MESH + 1 MESH": "RECABLEADO",
  "RECABLEADO + 1 MESH": "RECABLEADO",
  "RECABLEADO + CAMBIO DE ONT + CABLEADO MESH + 1 MESH": "RECABLEADO",
  "RECABLEADO + CABLEADO MESH - POSTVENTA": "RECABLEADO",
  "RECABLEADO POR CORTE CONCESIONARIA": "RECABLEADO",
  "RECABLEADO POR MANTENIMIENTO": "RECABLEADO",
  "RECABLEADO + 2 WIN BOX": "RECABLEADO",
  "RECABLEADO + 2 MESH": "RECABLEADO",

  // 5. REUBICACIÓN CON RESERVA
  "REUBICACION DE ROUTER CON RESERVA - POST VENTA": "REUBICACIÓN CON RESERVA",
  "REUBICACION DE ROUTER CON RESERVA POST VENTA": "REUBICACIÓN CON RESERVA",
  "REUBICACION CON RESERVA": "REUBICACIÓN CON RESERVA",

  // 6. REUBICACIÓN SIN RESERVA
  "REUBICACION DE ROUTER SIN RESERVA - POST VENTA": "REUBICACIÓN SIN RESERVA",
  "REUBICACION DE ROUTER SIN RESERVA POST VENTA": "REUBICACIÓN SIN RESERVA",
  "REUBICACION SIN RESERVA": "REUBICACIÓN SIN RESERVA",
  "REUBICACION SIN RESERVA / CON RESERVA + CABLEADO MESH - POSTVENTA": "REUBICACIÓN SIN RESERVA",

  // 7. TRASALDO EN CONDOMINIO / TRASLADO EN CONDOMINIO
  "TRASLADO DE SERVICIOS POR MUDANZA EN CONDOMINIO - POST VENTA": "TRASALDO EN CONDOMINIO",
  "TRASLADO DE SERVICIOS POR MUDANZA EN CONDOMINIO POST VENTA": "TRASALDO EN CONDOMINIO",
  "TRASALDO EN CONDOMINIO": "TRASALDO EN CONDOMINIO",
  "TRASLADO EN CONDOMINIO": "TRASALDO EN CONDOMINIO",

  // 8. TRASLADO
  "TRASLADO DE SERVICIOS POR MUDANZA EN RESIDENCIALES - POST VENTA": "TRASLADO",
  "TRASLADO DE SERVICIOS POR MUDANZA EN RESIDENCIALES POST VENTA": "TRASLADO",
  "TRASLADO": "TRASLADO",
  "TRASLADO + CAMBIO ONT": "TRASLADO",
  "TRASLADO + 1 MESH": "TRASLADO",
  "TRASLADO + CABLEADO MESH - POSTVENTA": "TRASLADO",
  "TRASLADO + 1 WIN BOX": "TRASLADO",
  "TRASLADO + CAMBIO DE ONT + 1 MESH": "TRASLADO",
  "TRASLADO + CABLEADO MESH + 01 MESH + 1 APARATO TELEFONICO": "TRASLADO",
  "TRASLADO + CABLEADO MESH + 1 MESH": "TRASLADO",
  "TRASLADO + 1 APARATO TELEFONICO": "TRASLADO",

  // 9. PEX
  "PRUEBA DE SERVICIO - CTO CON POTENCIA DEGRADADA": "PEX",
  "PRUEBA DE SERVICIO - CTO CON PUERTOS DEGRADADOS": "PEX",
  "PRUEBA DE SERVICIO": "PEX",
  "PRUEBAS DE SERVICIO": "PEX",
  "PRUEBA DE SERVICIO - CTO O NAP CON PROBLEMAS DE POTENCIA EN PUERTOS": "PEX",
  "PRUEBA DE SERVICIO - CTO SIN POTENCIA": "PEX",
  "CONJUNTA FINALIZADA": "PEX",
  "CONJUNTA PEXT AVERIA": "PEX",
  "CONJUNTA PEXT": "PEX",
  "PRUEBA DE SERVICIO - CTO CON INTERMITENCIA": "PEX",
  "PRUEBA DE SERVICIO - NAP SIN POTENCIA": "PEX",
  "PRUEBA DE SERVICIO - NAP CON PUERTOS DEGRADADOS": "PEX",
  "PRUEBA DE SERVICIO - NAP CON POTENCIA DEGRADADA": "PEX",
  "TRABAJOS PLANTA EXTERNA": "PEX",

  // 10. ADICIONAL
  "INSTALACION DE SPLITERS 1X2": "ADICIONAL",
  "INSTALACION DE SPLITTERS 1X2": "ADICIONAL",
  "SPLITTER": "ADICIONAL",
  "SPLITER": "ADICIONAL",
  "CAMBIO DE MESH ADICIONAL": "ADICIONAL",
  "CAMBIO DE TV BOX ADICIONAL": "ADICIONAL",
  "CAMBIO DE ONT POR REPOSICION ADICIONAL": "ADICIONAL",
  "CABLEADO UTP CAT 6 ADICIONAL - POST VENTA": "ADICIONAL",
  "CABLEADO UTP CAT 6 ADICIONAL POST VENTA": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE FONO WIN - ADICIONAL": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE FONO WIN ADICIONAL": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE TV BOX - ADICIONAL": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE TV BOX ADICIONAL": "ADICIONAL",
  "SERVICIOS DE ENTREGA Y CONFIGURACION MESH - ADICIONAL": "ADICIONAL",
  "SERVICIOS DE ENTREGA Y CONFIGURACION MESH ADICIONAL": "ADICIONAL",
  "KIT WIFI PRO (AL CONTADO)": "ADICIONAL",
  "KIT WIFI PRO AL CONTADO": "ADICIONAL",
  "CABLEADO UTP AL CONTADO": "ADICIONAL",
  "CABLEADO 02 MESH + ENTREGA Y CONFIG 1 MESH - POSTVENTA": "ADICIONAL",
  "CABLEADO 02 MESH + ENTREGA Y CONFIG 2 MESH - POSTVENTA": "ADICIONAL",
  "CABLEADO MESH + ENTREGA Y CONFIG 1 MESH-POSTVENTA": "ADICIONAL",
  "CABLEADO MESH + ENTREGA Y CONFIG 2 MESH - POSTVENTA": "ADICIONAL",
  "1 APARATO TELEFONICO": "ADICIONAL",
  "1 MESH": "ADICIONAL",
  "2 MESH": "ADICIONAL",
  "1 WIN BOX": "ADICIONAL",
  "2 WIN BOX": "ADICIONAL",

  // 11. VISITA EXTERNA
  "CAMBIO DE EQUIPO ONT": "VISITA EXTERNA",
  "CAMBIO DE ONT ADICIONAL": "VISITA EXTERNA",
  "CAMBIO FONOWIN": "VISITA EXTERNA",
  "CAMBIO DE FONO WIN": "VISITA EXTERNA",
  "CAMBIO DE PHONOWIN": "VISITA EXTERNA",
  "CAMBIO DE CONECTOR EN CTO/NAP": "VISITA EXTERNA",
  "CAMBIO DE CONECTOR EN CTO NAP": "VISITA EXTERNA",
  "CAMBIO DE CONECTOR CTO/NAP": "VISITA EXTERNA",
  "CAMBIO DE CONECTOR EN ROSETA": "VISITA EXTERNA",
  "ADAPTADOR ROSETA": "VISITA EXTERNA",
  "CAMBIO DE CABLE PATCH CORD": "VISITA EXTERNA",
  "CAMBIO DE CABLE PATCHCORD": "VISITA EXTERNA",
  "CAMBIO DE CABLE PACHTCORD": "VISITA EXTERNA",
  "CAMBIO DE CABLE PATCH-CORD": "VISITA EXTERNA",
  "CAMBIO DE PATCH CORD": "VISITA EXTERNA",
  "CAMBIO DE PATCHCORD": "VISITA EXTERNA",
  "PATCH CORD": "VISITA EXTERNA",
  "PATCHCORD": "VISITA EXTERNA",
  "PATCH CORD - POST VENTA": "VISITA EXTERNA",
  "PATCH CORD POST VENTA": "VISITA EXTERNA",
  "CAMBIO DE ACOPLADOR": "VISITA EXTERNA",
  "ACOMODO DE FIBRA": "VISITA EXTERNA",
  "ACONDICIONAMIENTO DE DROP": "VISITA EXTERNA",
  "ATENCION DE AVERIAS ULTIMA MILLA": "VISITA EXTERNA",
  "ATENCION DE AVERIA ULTIMA MILLA": "VISITA EXTERNA",
  "CAMBIO DE TV BOX": "VISITA EXTERNA",
  "CAMBIO DE WINBOX": "VISITA EXTERNA",
  "CONFIGURACION WINBOX": "VISITA EXTERNA",
  "CONFIGURACION MESH": "VISITA EXTERNA",
  "CONFIGURACION ONT": "VISITA EXTERNA",
  "CONFIGURACION PHONOWIN": "VISITA EXTERNA",
  "CAMBIO DE EQUIPO MESH": "VISITA EXTERNA",
  "CAMBIO MESH - NO SINCRONIZA / NO EMITE SEÑAL": "VISITA EXTERNA",
  "CAMBIO MESH - MESH INOPERATIVO": "VISITA EXTERNA",
  "CAMBIO MESH - PUERTOS AVERIADOS": "VISITA EXTERNA",
  "CAMBIO DE ONT - ONT INOPERATIVA": "VISITA EXTERNA",
  "CAMBIO DE ONT - NO SINCRONIZA / NO EMITE SEÑAL": "VISITA EXTERNA",
  "CAMBIO DE ONT - CARGADOR MALOGRADO": "VISITA EXTERNA",
  "CAMBIO DE ONT - ONT ROBADA": "VISITA EXTERNA",
  "CAMBIO DE ONT - PUERTOS AVERIADOS": "VISITA EXTERNA",
  "CAMBIO ONT - POST VENTA": "VISITA EXTERNA",
  "CAMBIO ONT POST VENTA": "VISITA EXTERNA",
  "CAMBIO DE ONT + 1 WIN BOX": "VISITA EXTERNA",
  "CABLEADO MESH - POSTVENTA": "VISITA EXTERNA",
  "CABLEADO MESH POSTVENTA": "VISITA EXTERNA",
  "CABLEADO MESH + 1 WIN BOX": "VISITA EXTERNA",
  "CABLEADO MESH + 1 MESH + CAMBIO DE ONT": "VISITA EXTERNA",
  "CABLEADO 02 MESH - POSTVENTA": "VISITA EXTERNA",
  "CABLEADO 03 MESH - POSTVENTA": "VISITA EXTERNA",
  "CABLEADO MESH + 2 MESH + CAMBIO DE ONT": "VISITA EXTERNA",
  "CABLEADO MESH + 2 WIN BOX": "VISITA EXTERNA",
  "ENTREGA + CONFIG 1 WIN BOX": "VISITA EXTERNA",
  "ENTREGA + CONFIG 2 WIN BOX": "VISITA EXTERNA",
  "ENTREGA + CONFIG 1 MESH": "VISITA EXTERNA",
  "ENTREGA + CONFIG 2 MESH": "VISITA EXTERNA",
  "ENTREGA + CONFIG 1 MESH + 1 WIN BOX": "VISITA EXTERNA",
  "ENTREGA + CONFIG 1 MESH + APARATO TEL": "VISITA EXTERNA",
  "ENTREGA + CONFIG 1 APARATO TELEFONICO": "VISITA EXTERNA",
  "ASISTENCIA WIN TV": "VISITA EXTERNA",
  "ASISTENCIA DGO": "VISITA EXTERNA",
  "CONFIG CREDENCIALES DGO": "VISITA EXTERNA",
  "CONFIG CREDENCIALES APPS": "VISITA EXTERNA",
  "CONFIG CREDENCIALES WIN TV": "VISITA EXTERNA",
  "WINBOX - CONTROL DEFECT": "VISITA EXTERNA",
  "CLIENTE CON SERVICIO - POTENCIA OPTIMA": "VISITA EXTERNA",
  "CLIENTE CON SERVICIO POTENCIA OPTIMA": "VISITA EXTERNA",
};

/**
 * Normaliza un string para comparación (sin tildes, mayúsculas, sin puntuación extra)
 */
export function normalizarTipificacion(str?: string): string {
  if (!str) return "";
  return str
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // quitar tildes
    .replace(/[^A-Z0-9\s-]/g, " ")   // caracteres especiales a espacios
    .replace(/\s+/g, " ")            // espacios múltiples a uno
    .trim();
}

/**
 * Comprueba si un valor coincide directamente con alguno de los tipos oficiales del catálogo
 */
export function matchWithCatalog(
  val?: string,
  dynamicCatalog: string[] = TIPOS_TRABAJO_CATALOGO
): string | null {
  if (!val) return null;
  const normVal = normalizarTipificacion(val);
  if (!normVal) return null;

  for (const cat of dynamicCatalog) {
    if (normalizarTipificacion(cat) === normVal) {
      return cat;
    }
  }
  return null;
}

/**
 * Empareja automáticamente el Tipo de Liquidación (Tipificación WIN / Motivo de Finalización / Avería)
 * con su correspondiente Tipo de Trabajo oficial de la tabla `tipos_trabajo`.
 */
export function mapTipificacionWinToTipoTrabajo(
  tipificacionWin?: string,
  extraContext?: string
): string | null {
  if (!tipificacionWin && !extraContext) return null;
  const norm = normalizarTipificacion(tipificacionWin);
  const normExtra = normalizarTipificacion(`${tipificacionWin || ""} ${extraContext || ""}`);

  if (!norm && !normExtra) return null;

  // 1. Coincidencia directa si ya es uno de los tipos de trabajo oficiales de la tabla
  for (const cat of TIPOS_TRABAJO_CATALOGO) {
    if (norm === normalizarTipificacion(cat)) {
      return cat;
    }
  }

  // 2. Búsqueda exacta en el diccionario predefinido
  if (norm && TIPIFICACION_A_AREA_MAP[norm]) {
    return TIPIFICACION_A_AREA_MAP[norm];
  }

  // 3. GARANTIA NO REALIZADA
  if (
    norm.includes("GARANTIA") &&
    (norm.includes("NO REALIZADA") ||
      norm.includes("CANCELADA") ||
      norm.includes("NO EJECUTADA") ||
      norm.includes("ANULADA") ||
      norm.includes("OBSERVADA") ||
      norm.includes("REPROGRAMADA"))
  ) {
    return "GARANTIA NO REALIZADA";
  }

  // 4. GARANTIA
  if (
    norm.includes("GARANTIA") ||
    norm.includes("REITERADA") ||
    norm.includes("FALLA RECURRENTE")
  ) {
    return "GARANTIA";
  }

  // 5. NORMALIZACIÓN
  if (
    norm.includes("NORMALIZACION") ||
    norm.includes("REMATRICULACION") ||
    norm.includes("MIGRA GAMER") ||
    norm.includes("MIGRACION") ||
    norm.includes("MEJORA TECNOLOGICA")
  ) {
    return "NORMALIZACIÓN";
  }

  // 6. RECABLEADO EN CONDOMINIO
  if (
    (norm.includes("RECABLEADO") && norm.includes("CONDOMINIO")) ||
    norm.includes("RECABLEADO EN CONDOMINIO") ||
    norm.includes("RECABLEADO CONDOMINIO")
  ) {
    return "RECABLEADO EN CONDOMINIO";
  }

  // 7. RECABLEADO (Residencial o general)
  if (
    norm.includes("RECABLEADO") ||
    norm.includes("CORTE MUNICIPAL") ||
    norm.includes("CORTE CONCESIONARIA") ||
    norm.includes("PROBLEMAS CON EL CABLEADO") ||
    norm.includes("REEMPLAZO DE DROP")
  ) {
    return "RECABLEADO";
  }

  // 8. REUBICACIÓN SIN RESERVA
  if (norm.includes("REUBICACION") && norm.includes("SIN RESERVA")) {
    return "REUBICACIÓN SIN RESERVA";
  }

  // 9. REUBICACIÓN CON RESERVA
  if (
    norm.includes("REUBICACION") &&
    (norm.includes("CON RESERVA") || norm.includes("RESERVA"))
  ) {
    return "REUBICACIÓN CON RESERVA";
  }

  // 10. TRASALDO EN CONDOMINIO / TRASLADO EN CONDOMINIO
  if (
    (norm.includes("TRASLADO") || norm.includes("TRASALDO")) &&
    norm.includes("CONDOMINIO")
  ) {
    return "TRASALDO EN CONDOMINIO";
  }

  // 11. TRASLADO (General / Residencial)
  if (
    norm.includes("TRASLADO") ||
    norm.includes("TRASALDO") ||
    norm.includes("MUDANZA")
  ) {
    return "TRASLADO";
  }

  // 12. PEX (Pruebas de Servicio, Conjuntas, Planta Externa, Puertos / CTO / NAP degradados o sin potencia)
  if (
    norm.includes("PRUEBA DE SERVICIO") ||
    norm.includes("PRUEBAS DE SERVICIO") ||
    norm.includes("CONJUNTA") ||
    norm.includes("PEX") ||
    norm.includes("PEXT") ||
    norm.includes("PLANTA EXTERNA") ||
    norm.includes("NAP SIN POTENCIA") ||
    norm.includes("NAP CON PUERTOS") ||
    norm.includes("CTO SIN POTENCIA") ||
    norm.includes("POTENCIA DEGRADADA") ||
    norm.includes("PUERTOS DEGRADADOS")
  ) {
    return "PEX";
  }

  // 13. ADICIONAL (Mesh adicional, TV box adicional, Splitters, Kit wifi, entregas de equipos postventa al contado)
  if (
    norm.includes("SPLITER") ||
    norm.includes("SPLITTER") ||
    norm.includes("KIT WIFI") ||
    norm.includes("ENTREGA + CONFIG") ||
    norm.includes("ENTREGA Y CONFIG") ||
    norm.includes("ADICIONAL") ||
    norm === "1 MESH" ||
    norm === "2 MESH" ||
    norm === "1 WIN BOX" ||
    norm === "2 WIN BOX" ||
    norm === "1 APARATO TELEFONICO" ||
    norm.includes("AL CONTADO")
  ) {
    return "ADICIONAL";
  }

  // 14. VISITA EXTERNA (Averías de última milla, conectores, rosetas, patch cord, ONT, mesh, etc.)
  if (
    norm.includes("CONECTOR") ||
    norm.includes("ROSETA") ||
    norm.includes("PATCH") ||
    norm.includes("ONT") ||
    norm.includes("MESH") ||
    norm.includes("WINBOX") ||
    norm.includes("TV BOX") ||
    norm.includes("FONO") ||
    norm.includes("PHONO") ||
    norm.includes("ACOMODO") ||
    norm.includes("ACONDICIONAMIENTO") ||
    norm.includes("DROP") ||
    norm.includes("POTENCIA") ||
    norm.includes("AVERIA") ||
    norm.includes("POST VENTA") ||
    norm.includes("POSTVENTA") ||
    norm.includes("DGO") ||
    norm.includes("CREDENCIALES") ||
    norm.includes("WIN TV") ||
    norm.includes("LOS ROJO") ||
    norm.includes("INTERMITENCIA") ||
    norm.includes("DESCARTE") ||
    norm.includes("MANTENIMIENTO") ||
    norm.includes("ASISTENCIA") ||
    norm.includes("VISITA EXTERNA") ||
    norm.includes("VISITA TECNICA") ||
    normExtra.includes("AVERIA") ||
    normExtra.includes("LOS ROJO") ||
    normExtra.includes("ONT") ||
    normExtra.includes("POTENCIA")
  ) {
    return "VISITA EXTERNA";
  }

  return "VISITA EXTERNA";
}

