/**
 * Mapeo oficial entre Motivo de Liquidación / Finalización / Avería de Fénix
 * y el Tipo de Trabajo Oficial según la tabla MySQL `tipos_trabajo` y la tabla `motivos`.
 */

const TIPOS_TRABAJO_OFICIALES = [
  "NORMALIZACIÓN",
  "RECABLEADO",
  "GARANTIA",
  "REUBICACIÓN CON RESERVA",
  "TRASLADO",
  "VISITA EXTERNA",
  "REUBICACIÓN SIN RESERVA",
  "GARANTIA NO REALIZADA",
  "RECABLEADO EN CONDOMINIO",
  "TRASALDO EN CONDOMINIO",
  "PEX",
  "ADICIONAL"
];

// Matriz de homologación de motivos de liquidación a Tipos de Trabajo
const MOTIVO_TO_TIPO_TRABAJO = {
  // 1. NORMALIZACIÓN
  "NORMALIZACION": "NORMALIZACIÓN",
  "NORMALIZACION FINALIZADA": "NORMALIZACIÓN",
  "NORMALIZACION FINALIZADA BRAZO EXTENSOR": "NORMALIZACIÓN",
  "NORMALIZACION CANCELADA": "NORMALIZACIÓN",
  "REMATRICULACION ONT": "NORMALIZACIÓN",
  "MIGRA GAMER REALIZADO - POSTVENTA": "NORMALIZACIÓN",
  "MIGRA GAMER REALIZADO POSTVENTA": "NORMALIZACIÓN",
  "MIGRA GAMER SOLO ENTREGA": "NORMALIZACIÓN",
  "MIGRA GAMER": "NORMALIZACIÓN",
  "MIGRA XGSPON": "NORMALIZACIÓN",
  "CAMBIO DE ONT - MEJORA TECNOLOGICA": "NORMALIZACIÓN",
  "CAMBIO DE ONT MEJORA TECNOLOGICA": "NORMALIZACIÓN",
  "CAMBIO DE ONT - MEJORA TECNOLOGICA - POSTVENTA": "NORMALIZACIÓN",
  "CAMBIO DE ONT MEJORA TECNOLOGICA POSTVENTA": "NORMALIZACIÓN",
  "MEJORA TECNOLOGICA MESH": "NORMALIZACIÓN",
  "MEJORA TECNOLOGICA ONT": "NORMALIZACIÓN",

  // 2. GARANTIA Y GARANTIA NO REALIZADA
  "GARANTIA": "GARANTIA",
  "GARANTIA REALIZADA": "GARANTIA",
  "POST VENTA GARANTIA": "GARANTIA",
  "GARANTIA NO REALIZADA": "GARANTIA NO REALIZADA",
  "GARANTIA CANCELADA": "GARANTIA NO REALIZADA",
  "GARANTIA REPROGRAMADA": "GARANTIA NO REALIZADA",
  "GARANTIA OBSERVADA": "GARANTIA NO REALIZADA",

  // 3. RECABLEADO EN CONDOMINIO
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO - VISITA TECNICA": "RECABLEADO EN CONDOMINIO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO VISITA TECNICA": "RECABLEADO EN CONDOMINIO",
  "RECABLEADO EN CONDOMINIO": "RECABLEADO EN CONDOMINIO",
  "RECABLEADO CONDOMINIO": "RECABLEADO EN CONDOMINIO",

  // 4. RECABLEADO
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL - VISITA TECNICA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL VISITA TECNICA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL - POST VENTA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO RESIDENCIAL POST VENTA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO - POST VENTA": "RECABLEADO",
  "SERVICIO COMPLETO DE RECABLEADO EN ABONADO CONDOMINIO POST VENTA": "RECABLEADO",
  "RECABLEADO - AVERIADO POR TERCEROS": "RECABLEADO",
  "RECABLEADO AVERIADO POR TERCEROS": "RECABLEADO",
  "RECABLEADO - CLIENTE MIGRA A OTRA CTO": "RECABLEADO",
  "RECABLEADO CLIENTE MIGRA A OTRA CTO": "RECABLEADO",
  "RECABLEADO - POST VENTA": "RECABLEADO",
  "RECABLEADO POST VENTA": "RECABLEADO",
  "RECABLEADO - AVERIADO POR CLIENTE": "RECABLEADO",
  "RECABLEADO AVERIADO POR CLIENTE": "RECABLEADO",
  "RECABLEADO - CAMBIO DE POSTE": "RECABLEADO",
  "RECABLEADO CAMBIO DE POSTE": "RECABLEADO",
  "RECABLEADO - NO CUMPLE POLITICAS DE INSTALACION": "RECABLEADO",
  "RECABLEADO NO CUMPLE POLITICAS DE INSTALACION": "RECABLEADO",
  "RECABLEADO + CAMBIO DE ONT POST VENTA": "RECABLEADO",
  "RECABLEADO CAMBIO DE ONT POST VENTA": "RECABLEADO",
  "RECABLEADO CORTE MUNICIPAL": "RECABLEADO",
  "RECABLEADO - DESCONEXION DEL CLIENTE": "RECABLEADO",
  "RECABLEADO DESCONEXION DEL CLIENTE": "RECABLEADO",
  "RECABLEADO + WIN BOX": "RECABLEADO",
  "RECABLEADO + CABLEADO MESH + 1 MESH": "RECABLEADO",
  "RECABLEADO + 1 MESH": "RECABLEADO",
  "RECABLEADO + CAMBIO DE ONT + CABLEADO MESH + 1 MESH": "RECABLEADO",
  "RECABLEADO + CABLEADO MESH - POSTVENTA": "RECABLEADO",
  "RECABLEADO POR CORTE CONCESIONARIA": "RECABLEADO",
  "RECABLEADO POR MANTENIMIENTO": "RECABLEADO",
  "RECABLEADO + 2 WIN BOX": "RECABLEADO",
  "RECABLEADO + 2 MESH": "RECABLEADO",

  // 5. REUBICACIÓN CON RESERVA
  "REUBICACION DE ROUTER CON RESERVA - POST VENTA": "REUBICACIÓN CON RESERVA",
  "REUBICACION DE ROUTER CON RESERVA POST VENTA": "REUBICACIÓN CON RESERVA",
  "REUBICACION CON RESERVA": "REUBICACIÓN CON RESERVA",

  // 6. REUBICACIÓN SIN RESERVA
  "REUBICACION DE ROUTER SIN RESERVA - POST VENTA": "REUBICACIÓN SIN RESERVA",
  "REUBICACION DE ROUTER SIN RESERVA POST VENTA": "REUBICACIÓN SIN RESERVA",
  "REUBICACION SIN RESERVA": "REUBICACIÓN SIN RESERVA",
  "REUBICACION SIN RESERVA / CON RESERVA + CABLEADO MESH - POSTVENTA": "REUBICACIÓN SIN RESERVA",

  // 7. TRASALDO EN CONDOMINIO
  "TRASLADO DE SERVICIOS POR MUDANZA EN CONDOMINIO - POST VENTA": "TRASALDO EN CONDOMINIO",
  "TRASLADO DE SERVICIOS POR MUDANZA EN CONDOMINIO POST VENTA": "TRASALDO EN CONDOMINIO",
  "TRASALDO EN CONDOMINIO": "TRASALDO EN CONDOMINIO",
  "TRASLADO EN CONDOMINIO": "TRASALDO EN CONDOMINIO",

  // 8. TRASLADO
  "TRASLADO DE SERVICIOS POR MUDANZA EN RESIDENCIALES - POST VENTA": "TRASLADO",
  "TRASLADO DE SERVICIOS POR MUDANZA EN RESIDENCIALES POST VENTA": "TRASLADO",
  "TRASLADO": "TRASLADO",
  "TRASLADO + CAMBIO ONT": "TRASLADO",
  "TRASLADO + 1 MESH": "TRASLADO",
  "TRASLADO + CABLEADO MESH - POSTVENTA": "TRASLADO",
  "TRASLADO + 1 WIN BOX": "TRASLADO",
  "TRASLADO + CAMBIO DE ONT + 1 MESH": "TRASLADO",
  "TRASLADO + CABLEADO MESH + 01 MESH + 1 APARATO TELEFONICO": "TRASLADO",
  "TRASLADO + CABLEADO MESH + 1 MESH": "TRASLADO",
  "TRASLADO + 1 APARATO TELEFONICO": "TRASLADO",

  // 9. PEX
  "PRUEBA DE SERVICIO - CTO CON POTENCIA DEGRADADA": "PEX",
  "PRUEBA DE SERVICIO - CTO CON PUERTOS DEGRADADOS": "PEX",
  "PRUEBA DE SERVICIO": "PEX",
  "PRUEBAS DE SERVICIO": "PEX",
  "PRUEBA DE SERVICIO - CTO O NAP CON PROBLEMAS DE POTENCIA EN PUERTOS": "PEX",
  "PRUEBA DE SERVICIO - CTO SIN POTENCIA": "PEX",
  "CONJUNTA FINALIZADA": "PEX",
  "CONJUNTA PEXT AVERIA": "PEX",
  "CONJUNTA PEXT": "PEX",
  "PRUEBA DE SERVICIO - CTO CON INTERMITENCIA": "PEX",
  "PRUEBA DE SERVICIO - NAP SIN POTENCIA": "PEX",
  "PRUEBA DE SERVICIO - NAP CON PUERTOS DEGRADADOS": "PEX",
  "PRUEBA DE SERVICIO - NAP CON POTENCIA DEGRADADA": "PEX",
  "TRABAJOS PLANTA EXTERNA": "PEX",

  // 10. ADICIONAL
  "INSTALACION DE SPLITERS 1X2": "ADICIONAL",
  "INSTALACION DE SPLITTERS 1X2": "ADICIONAL",
  "SPLITTER": "ADICIONAL",
  "SPLITER": "ADICIONAL",
  "CAMBIO DE MESH ADICIONAL": "ADICIONAL",
  "CAMBIO DE TV BOX ADICIONAL": "ADICIONAL",
  "CAMBIO DE ONT POR REPOSICION ADICIONAL": "ADICIONAL",
  "CABLEADO UTP CAT 6 ADICIONAL - POST VENTA": "ADICIONAL",
  "CABLEADO UTP CAT 6 ADICIONAL POST VENTA": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE FONO WIN - ADICIONAL": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE FONO WIN ADICIONAL": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE TV BOX - ADICIONAL": "ADICIONAL",
  "SERVICIO DE ENTREGA Y CONFIGURACION DE TV BOX ADICIONAL": "ADICIONAL",
  "SERVICIOS DE ENTREGA Y CONFIGURACION MESH - ADICIONAL": "ADICIONAL",
  "SERVICIOS DE ENTREGA Y CONFIGURACION MESH ADICIONAL": "ADICIONAL",
  "KIT WIFI PRO (AL CONTADO)": "ADICIONAL",
  "KIT WIFI PRO AL CONTADO": "ADICIONAL",
  "CABLEADO UTP AL CONTADO": "ADICIONAL",
  "CABLEADO 02 MESH + ENTREGA Y CONFIG 1 MESH - POSTVENTA": "ADICIONAL",
  "CABLEADO 02 MESH + ENTREGA Y CONFIG 2 MESH - POSTVENTA": "ADICIONAL",
  "CABLEADO MESH + ENTREGA Y CONFIG 1 MESH-POSTVENTA": "ADICIONAL",
  "CABLEADO MESH + ENTREGA Y CONFIG 2 MESH - POSTVENTA": "ADICIONAL",
  "1 APARATO TELEFONICO": "ADICIONAL",
  "1 MESH": "ADICIONAL",
  "1 TV BOX": "ADICIONAL",
  "INSTALACION 01 MESH": "ADICIONAL",
  "INSTALACION 02 MESH": "ADICIONAL",
  "INSTALACION 03 MESH": "ADICIONAL",
  "INSTALACION 04 MESH": "ADICIONAL",

  // 11. VISITA EXTERNA (MOTIVOS COMUNES Y DETALLADOS)
  "CAMBIO DE CONECTOR EN CTO/NAP": "VISITA EXTERNA",
  "CAMBIO DE CONECTOR CTO/NAP": "VISITA EXTERNA",
  "CAMBIO DE CONECTOR EN ROSETA": "VISITA EXTERNA",
  "CAMBIO DE CONECTOR ROSETA": "VISITA EXTERNA",
  "CAMBIO DE CABLE PATCH CORD": "VISITA EXTERNA",
  "CAMBIO DE ACOPLADOR": "VISITA EXTERNA",
  "ADAPTADOR ROSETA": "VISITA EXTERNA",
  "ACOMODO DE FIBRA": "VISITA EXTERNA",
  "CAMBIO DE EQUIPO MESH": "VISITA EXTERNA",
  "CAMBIO DE TV BOX": "VISITA EXTERNA",
  "CAMBIO DE EQUIPO ONT": "VISITA EXTERNA",
  "CAMBIO DE ONT ADICIONAL": "VISITA EXTERNA",
  "CAMBIO FONOWIN": "VISITA EXTERNA",
  "CONFIGURACION ONT": "VISITA EXTERNA",
  "CONFIGURACIÓN ONT": "VISITA EXTERNA",
  "CAMBIO DE WINBOX": "VISITA EXTERNA",
  "CAMBIO DE WIN BOX": "VISITA EXTERNA",
  "DESCARTE DE ONT": "VISITA EXTERNA",
  "DESCARTE DE FIBRA": "VISITA EXTERNA",
  "DESCARTE DE CABLEADO": "VISITA EXTERNA",
  "REPOSICION DE EQUIPO": "VISITA EXTERNA",
  "VISITA EXTERNA": "VISITA EXTERNA",
  "ATENCION DE AVERIA ULTIMA MILLA": "VISITA EXTERNA",
  "ATENCION DE AVERIAS ULTIMA MILLA": "VISITA EXTERNA"
};

function normalizeText(text) {
  if (!text) return "";
  return String(text)
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\w\s\+\-\/]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Determina el Tipo de Trabajo Oficial según el Motivo de Liquidación y contexto
 */
function resolverTipoTrabajoOficial(motivoLiquidacion, motivoAveria = "", estado = "") {
  const normEstado = String(estado || "").toLowerCase().trim();
  const isFinalizada = normEstado.includes("finaliz") || normEstado.includes("liquid") || normEstado.includes("termin") || normEstado.includes("cerrad") || normEstado.includes("fenix");

  // Si la orden no está finalizada, no tiene tipo de trabajo de liquidación
  if (!isFinalizada) {
    return null;
  }

  const normLiq = normalizeText(motivoLiquidacion);
  const normAveria = normalizeText(motivoAveria);

  // 1. Coincidencia directa en matriz
  if (normLiq && MOTIVO_TO_TIPO_TRABAJO[normLiq]) {
    return MOTIVO_TO_TIPO_TRABAJO[normLiq];
  }

  // 2. Coincidencia parcial inteligente por palabras clave
  if (normLiq.includes("RECABLEADO") || normLiq.includes("RE CABLEADO")) {
    if (normLiq.includes("CONDOMINIO")) return "RECABLEADO EN CONDOMINIO";
    return "RECABLEADO";
  }
  if (normLiq.includes("TRASLADO") || normLiq.includes("MUDANZA")) {
    if (normLiq.includes("CONDOMINIO")) return "TRASALDO EN CONDOMINIO";
    return "TRASLADO";
  }
  if (normLiq.includes("REUBICACION")) {
    if (normLiq.includes("CON RESERVA")) return "REUBICACIÓN CON RESERVA";
    if (normLiq.includes("SIN RESERVA")) return "REUBICACIÓN SIN RESERVA";
    return "REUBICACIÓN CON RESERVA";
  }
  if (normLiq.includes("NORMALIZACION") || normLiq.includes("MIGRA") || normLiq.includes("MEJORA TECNOLOGICA")) {
    return "NORMALIZACIÓN";
  }
  if (normLiq.includes("GARANTIA")) {
    if (normLiq.includes("NO REALIZADA") || normLiq.includes("CANCELADA") || normLiq.includes("OBSERVADA")) {
      return "GARANTIA NO REALIZADA";
    }
    return "GARANTIA";
  }
  if (normLiq.includes("PRUEBA DE SERVICIO") || normLiq.includes("PEX") || normLiq.includes("PLANTA EXTERNA") || normAveria.includes("PLANTA EXTERNA")) {
    return "PEX";
  }
  if (normLiq.includes("ADICIONAL") || normLiq.includes("SPLITTER") || normLiq.includes("SPLITER") || normLiq.includes("AL CONTADO")) {
    return "ADICIONAL";
  }
  if (normLiq.includes("CAMBIO DE") || normLiq.includes("CONFIGURACION") || normLiq.includes("CONECTOR") || normLiq.includes("ROSETA") || normLiq.includes("PATCH") || normLiq.includes("ACOPLADOR") || normLiq.includes("WINBOX") || normLiq.includes("MESH") || normLiq.includes("ONT")) {
    return "VISITA EXTERNA";
  }

  // 3. Si no hay motivo de liquidación pero la avería es Planta Externa
  if (normAveria.includes("PLANTA EXTERNA")) return "PEX";
  if (normAveria.includes("TRASLADO")) return "TRASLADO";

  return "VISITA EXTERNA"; // Categoría estándar de atención de averías finalizadas
}

module.exports = {
  TIPOS_TRABAJO_OFICIALES,
  resolverTipoTrabajoOficial
};
